---

- name: Deploying app
  hosts: app
  tasks:
    - name: Download app from github
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/muxund/reddit
        version: monolith
      notify: restart puma

    - name: installing bundle on app-server
      bundler:
        state: present
        chdir: /home/muxund/reddit

  handlers:
    - name: restart puma
      become: true
      systemd: name=puma state=restarted


