---
# tasks file for app
- name: Copy unit file puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config to db connections
  template:
    src: db_config.j2
    dest: /home/muxund/db_config
    owner: muxund
    group: muxund

- name: enable puma для app
  systemd: name=puma enabled=yes

