---
- name: Конфигурируем хост app
  hosts: app
  become: true
  vars:
    db_host: 10.132.0.54
  tasks:
    - name: Копируем юнит пума-сервис на app
      copy:
        src:   files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Добавляем конфиг подключения к бд на app
      template:
        src: templates/db_config.j2
        dest: /home/muxund/db_config
        owner: muxund
        group: muxund

    - name: enable puma для app
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    service: name=puma state=restarted

