---
- name: Config host and deploy application # Описание сценария
  hosts: all # Хосты, на которых выполятся таски
  vars:
    mongo_bind_ip: 0.0.0.0 # переменная задается в vars
    db_host: 10.132.0.42

  tasks: # блок тасков(заданий)
    - name: Change mongo config file
      become: true # выполняем задание от рута
      template:
        src:  templates/mongod.conf.j2 # путь до шаблона
        dest: /etc/mongod.conf # целевой путь на удаленном хосте
        mode: 0644  # права на файл
      tags: db-tag   # тэги задания 
      notify: restart mongod

    - name: Add unit file for puma
      become: true
      copy:
        src:   files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: 0644
      tags: app-tag
      notify: reload puma

    - name: Add config for db connection
      template:
        src: templates/db_config.j2
        dest: /home/muxund/db_config
      tags: app-tag

    - name: enabe puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: fetch the latest version of app
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/muxund/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/muxund/reddit # <-- В какой директории выполнить команду bundle
      tags: deploy-tag   


  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
    
  - name: reload puma
    become: true
    service: name=puma state=restarted 
    
